"""add blacklisted tokens table

Revision ID: 41e673ae00f9
Revises: 3eb23b66ae73
Create Date: 2026-04-22 10:38:50.459896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '41e673ae00f9'
down_revision: Union[str, Sequence[str], None] = '3eb23b66ae73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklisted_tokens',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column(
                        'token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('blacklisted_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('token')
                    )
    op.alter_column('products', 'Product_Description',
                    new_column_name='product_description')
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table('blacklisted_tokens')
    op.alter_column('products', 'product_Description',
                    new_column_name='Product_Description')  # ← reversed!
