"""add product category fields

Revision ID: b8c45e8bd806
Revises: 41e673ae00f9
Create Date: 2026-05-13 03:17:28.654284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b8c45e8bd806'
down_revision: Union[str, Sequence[str], None] = '41e673ae00f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column(
        'category', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('products', sa.Column(
        'style', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('products', sa.Column(
        'pieces', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('products', sa.Column(
        'fabric_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'fabric_type')
    op.drop_column('products', 'pieces')
    op.drop_column('products', 'style')
    op.drop_column('products', 'category')
    # ### end Alembic commands ###
