"""initial tables

Revision ID: da533e25b829
Revises: 
Create Date: 2026-04-07 22:39:48.629247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da533e25b829'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart')
    # ✅ Fixed - fills existing rows with current timestamp first
    op.add_column('products', sa.Column('created_at', sa.DateTime(),
                  nullable=False, server_default=sa.func.now()))
    op.alter_column('products', 'Product_Description',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('products', 'price',
                    existing_type=sa.INTEGER(),
                    type_=sa.Numeric(precision=10, scale=2),
                    existing_nullable=False)
    op.alter_column('products', 'img',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.drop_index(op.f('ix_products_collection'),
                  table_name='products', if_exists=True)
    op.drop_column('products', 'collection')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column(
        'collection', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_products_collection'),
                    'products', ['collection'], unique=False)
    op.alter_column('products', 'img',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('products', 'price',
                    existing_type=sa.Numeric(precision=10, scale=2),
                    type_=sa.INTEGER(),
                    existing_nullable=False)
    op.alter_column('products', 'Product_Description',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.drop_column('products', 'created_at')
    op.create_table('cart',
                    sa.Column('productid_in_cart', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('quantity', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('cartid', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.ForeignKeyConstraint(['productid_in_cart'], [
                        'products.id'], name=op.f('cart_productid_in_cart_fkey')),
                    sa.PrimaryKeyConstraint('cartid', name=op.f('cart_pkey'))
                    )
    # ### end Alembic commands ###
